export const STAT_COLUMNS = [
    { key: 'Mins', label: 'Mins', width: 50 },
    { key: 'PTS', label: 'PTS', width: 50 },
    { key: 'FG', label: 'FG', width: 50 },
    { key: 'FGA', label: 'FGA', width: 50 },
    { key: 'FGpct', label: 'FG%', width: 50 },
    { key: '2PM', label: '2PM', width: 50 },
    { key: '2PA', label: '2PA', width: 50 },
    { key: 'twoPTpct', label: '2PT%', width: 50 },
    { key: '3PM', label: '3PM', width: 50 },
    { key: '3PA', label: '3PA', width: 50 },
    { key: 'threePTpct', label: '3PT%', width: 50 },
    { key: 'FTM', label: 'FTM', width: 50 },
    { key: 'FTA', label: 'FTA', width: 50 },
    { key: 'FTpct', label: 'FT%', width: 50 },
    { key: 'REB', label: 'REB', width: 50 },
    { key: 'AST', label: 'AST', width: 50 },
    { key: 'STL', label: 'STL', width: 50 },
    { key: 'BLK', label: 'BLK', width: 50 },
    { key: 'TOV', label: 'TOV', width: 50 },
    { key: 'PF', label: 'PF', width: 50 },
    { key: 'PLUSMINUS', label: '+/-', width: 50 },
  ];
  