const { initializeApp } = require("firebase/app");
const { getFirestore, doc, setDoc, collection, getDoc } = require("firebase/firestore");

const firebaseConfig = {
  apiKey: "AIzaSyBAtiQi_lIDAgOZwmWugJ3mf5TVVICVhTU",
  authDomain: "rklmobile.firebaseapp.com",
  projectId: "rklmobile",
  storageBucket: "rklmobile.firebasestorage.app",
  messagingSenderId: "369767637513",
  appId: "1:369767637513:web:c47b6a5083ef86cac78ed8",
  measurementId: "G-MYCM8WXQ6T",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// Team and Players Data
const teamData = {
  achievements: [], // No specific achievements listed
  nameChanges: [], // No name changes listed
  assistantCoach: null, // No assistant coach listed
  division: "B-B", // As per instruction
  gamesPlayed: 0,
  headCoach: "Lukas Šimkus",
  icon: "https://images.statsengine.playbyplay.api.geniussports.com/7f3bc241ed0943987f74d42eece210c6S1.png", // Placeholder left empty as requested
  losses: 0,
  ptsDifference: 0,
  ptsMinus: 0,
  ptsPlus: 0,
  standingPoints: 0,
  teamID: "kaunoTechnologijosUniversitetas", // Unique identifier
  teamManager: "Lukas Šimkus",
  teamName: "Kauno technologijos universitetas",
  teamPhoto: "https://images.statsengine.playbyplay.api.geniussports.com/7f3bc241ed0943987f74d42eece210c6S1.png", // Placeholder left empty as requested
  wins: 0
};


const players = [
  {
    firstName: "Laurynas",
    lastName: "Mačiulaitis",
    dob: "2004-01-14",
    position: "SG",
    age: 20,
    nationality: "LTU",
    height: 193,
    weight: 80,
    shirtNumber: 13,
    photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
    stats: {
      g: 0,
      mpg: 0,
      ppg: 0,
      "2apg": 0,
      "2mpg": 0,
      "2pPercent": 0,
      "3apg": 0,
      "3mpg": 0,
      "3pPercent": 0,
      ftapg: 0,
      ftmpg: 0,
      ftPercent: 0,
      rpg: 0,
      apg: 0,
      stpg: 0,
      topg: 0,
      blkpg: 0,
      fpg: 0,
      tfpg: 0,
      effpg: 0,
    },
  },
  {
    firstName: "Jodranas",
    lastName: "Jančiauskas",
    dob: "2007-01-09",
    position: "SF",
    age: 17,
    nationality: "LTU",
    height: 191,
    weight: 79,
    shirtNumber: 33,
    photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
    stats: {
      g: 0,
      mpg: 0,
      ppg: 0,
      "2apg": 0,
      "2mpg": 0,
      "2pPercent": 0,
      "3apg": 0,
      "3mpg": 0,
      "3pPercent": 0,
      ftapg: 0,
      ftmpg: 0,
      ftPercent: 0,
      rpg: 0,
      apg: 0,
      stpg: 0,
      topg: 0,
      blkpg: 0,
      fpg: 0,
      tfpg: 0,
      effpg: 0,
    },
  },
  {
  firstName: "Gustas",
  lastName: "Blinkinas",
  dob: "2004-05-06",
  position: "C",
  age: 18,
  nationality: "LTU",
  height: 203,
  weight: 94,
  shirtNumber: 36,
  photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
  stats: {
    g: 0,
    mpg: 0,
    ppg: 0,
    "2apg": 0,
    "2mpg": 0,
    "2pPercent": 0,
    "3apg": 0,
    "3mpg": 0,
    "3pPercent": 0,
    ftapg: 0,
    ftmpg: 0,
    ftPercent: 0,
    rpg: 0,
    apg: 0,
    stpg: 0,
    topg: 0,
    blkpg: 0,
    fpg: 0,
    tfpg: 0,
    effpg: 0,
  },
},
{
firstName: "Juozas",
lastName: "Juozaitis",
dob: "2006-09-19",
position: "C/PF",
age: 18,
nationality: "LTU",
height: 201,
weight: 88,
shirtNumber: 41,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Mantvydas",
lastName: "Kalinauskas",
dob: "2003-03-18",
position: "SF",
age: 21,
nationality: "LTU",
height: 186,
weight: 80,
shirtNumber: 42,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Kajus",
lastName: "Gerdžiūnas",
dob: "2007-02-01",
position: "SF",
age: 17,
nationality: "LTU",
height: 195,
weight: 98,
shirtNumber: 47,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Augustas",
lastName: "Gaivenis",
dob: "2003-06-28",
position: "PF",
age: 21,
nationality: "LTU",
height: 195,
weight: 87,
shirtNumber: 51,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Povilas",
lastName: "Gaidelis",
dob: "2002-01-10",
position: "SF",
age: 22,
nationality: "LTU",
height: 193,
weight: 83,
shirtNumber: 55,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Gabrielius",
lastName: "Kaubrys",
dob: "2004-12-20",
position: "PF",
age: 20,
nationality: "LTU",
height: 205,
weight: 85,
shirtNumber: 57,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Paulius",
lastName: "Lukaševičius",
dob: "2006-08-03",
position: "PG",
age: 18,
nationality: "LTU",
height: 182,
weight: 75,
shirtNumber: 61,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Vicas",
lastName: "Aleknavičius",
dob: "2002-05-23",
position: "SF",
age: 22,
nationality: "LTU",
height: 196,
weight: 93,
shirtNumber: 64,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Rokas",
lastName: "Kabašinskas",
dob: "2003-01-14",
position: "PG",
age: 21,
nationality: "LTU",
height: 183,
weight: 75,
shirtNumber: 77,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Martynas",
lastName: "Mejaras",
dob: "2005-06-02",
position: "SG",
age: 19,
nationality: "LTU",
height: 191,
weight: 80,
shirtNumber: 81,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Simas",
lastName: "Stonys",
dob: "2004-08-07",
position: "PG",
age: 20,
nationality: "LTU",
height: 185,
weight: 75,
shirtNumber: 85,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
{
firstName: "Ainaras",
lastName: "Buginas",
dob: "2002-05-12",
position: "SG",
age: 22,
nationality: "LTU",
height: 188,
weight: 70,
shirtNumber: 9,
photoURL: "https://www.rkl.lt/wp-content/uploads/2024/10/default_player_image.png",
stats: {
  g: 0,
  mpg: 0,
  ppg: 0,
  "2apg": 0,
  "2mpg": 0,
  "2pPercent": 0,
  "3apg": 0,
  "3mpg": 0,
  "3pPercent": 0,
  ftapg: 0,
  ftmpg: 0,
  ftPercent: 0,
  rpg: 0,
  apg: 0,
  stpg: 0,
  topg: 0,
  blkpg: 0,
  fpg: 0,
  tfpg: 0,
  effpg: 0,
},
},
  // Add more players here if needed...
];

async function uploadTeamAndPlayers() {
  const teamRef = doc(db, "teams", teamData.teamID);

  try {
    // Check if the team already exists
    const teamSnapshot = await getDoc(teamRef);
    if (teamSnapshot.exists()) {
      console.error(`Team with ID ${teamData.teamID} already exists. Aborting creation to avoid overwriting.`);
      return;
    }

    // Upload new team data
    await setDoc(teamRef, teamData);
    console.log(`New team '${teamData.teamName}' created successfully!`);

    // Upload players for the team
    const playersCollectionRef = collection(teamRef, "players");
    for (const player of players) {
      const playerRef = doc(playersCollectionRef, player.firstName + player.lastName);
      await setDoc(playerRef, {
        firstName: player.firstName,
        lastName: player.lastName,
        dob: player.dob,
        position: player.position,
        age: player.age,
        nationality: player.nationality,
        height: player.height,
        weight: player.weight,
        shirtNumber: player.shirtNumber,
        photoURL: player.photoURL,
        ...player.stats, // Spread stats into the document
      });
      console.log(`Uploaded player: ${player.firstName} ${player.lastName}`);
    }
    console.log("All players uploaded successfully!");
  } catch (error) {
    console.error("Error uploading team and players:", error);
  }
}

uploadTeamAndPlayers();
